# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: skedaddle_development
  #username: skedaddle
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: skedaddle_test

production:
  <<: *default
  database: skedaddle_production
  username: skedaddle
  password: <%= ENV["SKEDADDLE_DATABASE_PASSWORD"] %>
